apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtestingapp
  template:
    metadata:
      labels:
        app: loadtestingapp
    spec:
      containers:
        - name: loadtestingapp
          image: ostashev/xafloadtesting:latest